### ISSUE TITLE
can't build `lamdu`: on OSX 10.10.x, `ghc` v7.10.3

### ISSUE THREAD

**Issue by evandrix** [lamdu/lamdu#54] opened 2016-02-21 17:57 UTC
Made sure that `ftgl`, `leveldb` and `libiconv` were installed beforehand

Compiled with additional switches: `--extra-include-dirs=/opt/local/include --extra-lib-dirs=/opt/local/lib`
since '/opt' is the default/standard $PREFIX applied when using MacPorts

Following is the error log displayed:

```
Configuring Lamdu-0.1...
Preprocessing library Lamdu-0.1...
In-place registering Lamdu-0.1...
Preprocessing executable 'lamdu' for Lamdu-0.1...
Linking .stack-work/dist/x86_64-osx/Cabal-1.22.5.0/build/lamdu/lamdu ...
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _hs_iconv in libHSbase-4.8.2.0-HQfYBxpPvuw8OunzQu6JGM.a(iconv.o)
     (maybe you meant: _hs_iconv, _base_GHCziIOziEncodingziIconv_iconvEncodingzuloc_info , _base_GHCziIOziEncodingziIconv_iconvEncoding10_info , _base_GHCziIOziEncodingziIconv_iconvEncoding9_closure , _base_GHCziIOziEncodingziIconv_iconvEncodingzuloc_closure , _hs_iconv_close , _base_GHCziIOziEncodingziIconv_iconvEncodingzuloc1_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding8_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding7_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding11_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding5_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding2_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding8_info , _base_GHCziIOziEncodingziIconv_iconvEncoding10_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding9_info , _base_GHCziIOziEncodingziIconv_iconvEncoding7_info , _hs_iconv_open , _base_GHCziIOziEncodingziIconv_iconvEncoding2_info , _base_GHCziIOziEncodingziIconv_iconvEncoding4_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding4_info , _base_GHCziIOziEncodingziIconv_iconvEncoding11_info , _base_GHCziIOziEncodingziIconv_iconvEncodingzuloc1_info , _base_GHCziIOziEncodingziIconv_iconvEncoding3_closure )
  "_iconv_close", referenced from:
      _hs_iconv_close in libHSbase-4.8.2.0-HQfYBxpPvuw8OunzQu6JGM.a(iconv.o)
     (maybe you meant: _hs_iconv_close)
  "_iconv_open", referenced from:
      _hs_iconv_open in libHSbase-4.8.2.0-HQfYBxpPvuw8OunzQu6JGM.a(iconv.o)
     (maybe you meant: _hs_iconv_open)
  "_locale_charset", referenced from:
      _localeEncoding in libHSbase-4.8.2.0-HQfYBxpPvuw8OunzQu6JGM.a(PrelIOUtils.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by evandrix** [comment] 2016-02-21 18:48
Googling `osx _hs_iconv libHSbase`, I found similar issues encountered

- http://blog.omega-prime.co.uk/?p=96
- https://github.com/gibiansky/IHaskell/issues/563
- http://blog.poucet.org/2011/01/haskell-platform-on-mac-osx
- http://comments.gmane.org/gmane.comp.lang.haskell.cabal.devel/10001

**Comment by yairchu** [comment] 2016-02-22 07:44
@evandrix Did the solutions mentioned there worked for you? (Adding `--extra-lib-dir=/usr/lib` so it picks the system's iconv)

**Comment by evandrix** [comment] 2016-02-22 15:27
Nope, still failing, unfortunately; because although there's 2 copies of `iconv` - one @ `/usr/lib`, another @ `/opt/local/lib`, there are other dependent libs in `/opt/local/lib`, so I can't exclude it completely, i.e. I can't have the copy of `iconv` from `/usr/lib`, whilst other libs (except `iconv`, of course) from `/opt/local/lib` are also used together. I don't know how to configure, either by command-line switch or `$HOME/.stack/config.yaml`, it to work this way.

**Comment by yairchu** [comment] 2017-09-19 10:33
@evandrix some things have changed since the repot (Lamdu has a reproducible-build with [stack](https://docs.haskellstack.org), uses a newer GHC, doesn't use FTGL)

does Lamdu still not build for you?

**Comment by yairchu** [comment] 2017-09-20 10:16
Switching to `stack` and changing GHC versions has probably resolved this. Closing but if there are any problems still I'll reopen the issue.

**Closed by yairchu** 2017-09-20 10:16 UTC
Labels: CantBuild, OSX
