### ISSUE TITLE
Building on NixOS using stack fails

### ISSUE THREAD

**Issue by razvan-panda** [lamdu/lamdu#84] opened 2018-01-29 12:48 UTC
After adding the nix dependencies (possibly not all needed):

    nix:
      enable: true
      packages:
      - glew
      - glfw
      - xorg.libXxf86vm
      - xorg.libX11
      - xorg.libXi
      - xorg.libXrandr
      - xorg.libXcursor
      - xorg.libXinerama
      - mesa_glu
      - libglvnd
      - zlib.dev
      - zlib.out
      - ncurses

It fails on building the sub-project `nodejs-exec`, ticket here: https://github.com/lamdu/nodejs-exec/issues/1

**Comment by razvan-panda** [comment] 2018-01-29 16:10
With these dependencies only 1 error left but can't figure it out:

    nix:
      enable: true
      packages:
      - leveldb
      - glew
      - glfw2
      - xorg.libXext
      - xorg.libXxf86vm
      - xorg.libX11
      - xorg.libXi
      - xorg.libXrandr
      - xorg.libXcursor
      - xorg.libXinerama
      - mesa_glu
      - libglvnd
      - zlib.dev
      - zlib.out
      - ncurses

 > <command line>: can't load .so/.DLL for: /home/neo/Forks/lamdu/.stack-work/install/x86_64-linux-nix/lts-10.0/8.2.2/lib/x86_64-linux-ghc-8.2.2/libHSfreetype2-0.1.2-IRZyUyXh1OE8STY2at3A2f-ghc8.2.2.so (/home/neo/Forks/lamdu/.stack-work/install/x86_64-linux-nix/lts-10.0/8.2.2/lib/x86_64-linux-ghc-8.2.2/libHSfreetype2-0.1.2-IRZyUyXh1OE8STY2at3A2f-ghc8.2.2.so: undefined symbol: ft_strncmp)

It appears that the symbol ft_strncmp is not present in your fork.

**Comment by razvan-panda** [comment] 2018-01-29 16:43
Actually, ft_strncmp is present in the fork.

**Comment by yairchu** [comment] 2018-01-29 16:48
That's probably from "freetype", could that be the missing package?

**Comment by razvan-panda** [comment] 2018-01-29 16:51
@yairchu Yes it is from freetype sub-project but adding it to Nix packages does not fix the issue.

```
- location:
    git: https://github.com/lamdu/freetype2
    commit: 71941659a29fe353bf975aefeb1805417c8ab364
```

**Comment by razvan-panda** [comment] 2018-01-29 16:52
Actually ofc. it wouldn't fix the issue since it is already added as a subproject :)

**Comment by yairchu** [comment] 2018-02-06 09:46
Merged! I guess all these hashes would need to be updated when we update `stack.yaml`, right? How does one compute those sha values?

**Comment by razvan-panda** [comment] 2018-02-06 11:09
@yairchu Which hashes?

**Comment by yairchu** [comment] 2018-02-06 12:17
These:

https://github.com/lamdu/lamdu/blob/master/nix/AlgoW.nix#L11

**Comment by ysangkok** [comment] 2018-02-06 12:21
You can use [nix-prefetch-git](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchgit/nix-prefetch-git)

**Comment by yairchu** [comment] 2018-02-06 12:25
So iiuc things work now, right? :)

**Closed by yairchu** 2018-02-06 12:25 UTC

**Comment by razvan-panda** [comment] 2018-02-06 12:42
@yairchu yeah, the `sha256 = "15zk654b18lckcph5rahb0phrsk4fpbsd3wz6lhqyvnmcrsd3yih"` will not change because the input is the same git repository at a specific version. (Unless someone decides to force push haha)

**Comment by yairchu** [comment] 2018-02-12 11:02
I've just [updated stack](https://github.com/lamdu/lamdu/commit/0a2ef60281395051aee2dfeb186d1e828e287970) dependencies and updated the nix dependencies accordingly using `nix-prefetch-git`.

@razvan-panda @ysangkok 

Can you folks check I did it ok?

Also, do you think it could be possible to make the build work in NixOS within stack without .nix files? That could be a cleaner solution with easier maintenance and less room for error.

**Comment by razvan-panda** [comment] 2018-02-12 13:27
@yairchu nix-build now fails with:

> From https://github.com/lamdu/FreetypeGL
>  * branch            HEAD       -> FETCH_HEAD
> From https://github.com/lamdu/nodejs-exec
>  * branch            HEAD       -> FETCH_HEAD
> From https://github.com/lamdu/graphics-drawingcombinators
>  * branch            HEAD       -> FETCH_HEAD
> remote: Compressing objects: 100% (152/152), done.        
> remote: Compressing objects: 100% (18/18), done.        
> remote: Total 24 (delta 0), reused 11 (delta 0), pack-reused 0        
> From https://github.com/lamdu/lamdu-calculus
>  * branch            HEAD       -> FETCH_HEAD
> Switched to a new branch 'fetchgit'
> /nix/store/jlwil6bvy8bw1s4wxk59q17pwrg268k3-git-2.15.1/libexec/git-core/git-sh-i18n: line 22: .: /nix/store/jcygy2k3m9r52r7j3npj2v54zxgl39jd-gettext-0.19.8/bin/gettext.sh: cannot execute binary file
> Switched to a new branch 'fetchgit'
> Switched to a new branch 'fetchgit'
> /nix/store/jlwil6bvy8bw1s4wxk59q17pwrg268k3-git-2.15.1/libexec/git-core/git-sh-setup: line 93: eval_gettext: command not found
> /nix/store/jlwil6bvy8bw1s4wxk59q17pwrg268k3-git-2.15.1/libexec/git-core/git-sh-i18n: line 22: .: /nix/store/jcygy2k3m9r52r7j3npj2v54zxgl39jd-gettext-0.19.8/bin/gettext.sh: cannot execute binary file
> /nix/store/jlwil6bvy8bw1s4wxk59q17pwrg268k3-git-2.15.1/libexec/git-core/git-sh-i18n: line 22: .: /nix/store/jcygy2k3m9r52r7j3npj2v54zxgl39jd-gettext-0.19.8/bin/gettext.sh: cannot execute binary file
> remote: Total 47 (delta 1), reused 23 (delta 1), pack-reused 0        
> /nix/store/jlwil6bvy8bw1s4wxk59q17pwrg268k3-git-2.15.1/libexec/git-core/git-sh-setup: line 93: eval_gettext: command not found
> /nix/store/jlwil6bvy8bw1s4wxk59q17pwrg268k3-git-2.15.1/libexec/git-core/git-sh-setup: line 93: eval_gettext: command not found
> From https://github.com/lamdu/Algorithm-W-Step-By-Step
>  * branch            HEAD       -> FETCH_HEAD
> /nix/store/jlwil6bvy8bw1s4wxk59q17pwrg268k3-git-2.15.1/libexec/git-core/git-sh-i18n: line 22: .: /nix/store/jcygy2k3m9r52r7j3npj2v54zxgl39jd-gettext-0.19.8/bin/gettext.sh: cannot execute binary file
> /nix/store/jlwil6bvy8bw1s4wxk59q17pwrg268k3-git-2.15.1/libexec/git-core/git-sh-setup: line 93: eval_gettext: command not found
> /nix/store/jlwil6bvy8bw1s4wxk59q17pwrg268k3-git-2.15.1/libexec/git-core/git-sh-i18n: line 22: .: /nix/store/jcygy2k3m9r52r7j3npj2v54zxgl39jd-gettext-0.19.8/bin/gettext.sh: cannot execute binary file
> /nix/store/jlwil6bvy8bw1s4wxk59q17pwrg268k3-git-2.15.1/libexec/git-core/git-sh-i18n: line 22: .: /nix/store/jcygy2k3m9r52r7j3npj2v54zxgl39jd-gettext-0.19.8/bin/gettext.sh: cannot execute binary file
> /nix/store/jlwil6bvy8bw1s4wxk59q17pwrg268k3-git-2.15.1/libexec/git-core/git-sh-setup: line 93: eval_gettext: command not found
> /nix/store/jlwil6bvy8bw1s4wxk59q17pwrg268k3-git-2.15.1/libexec/git-core/git-sh-setup: line 93: eval_gettext: command not found
> Switched to a new branch 'fetchgit'
> /nix/store/jlwil6bvy8bw1s4wxk59q17pwrg268k3-git-2.15.1/libexec/git-core/git-sh-i18n: line 22: .: /nix/store/jcygy2k3m9r52r7j3npj2v54zxgl39jd-gettext-0.19.8/bin/gettext.sh: cannot execute binary file
> /nix/store/jlwil6bvy8bw1s4wxk59q17pwrg268k3-git-2.15.1/libexec/git-core/git-sh-setup: line 93: eval_gettext: command not found
> removing `.git'...
> /nix/store/1xi5xjj34d1inamh559ddq16ixgkwl1j-nix-prefetch-git: line 302: /nix/store/dhmqrk1mj2kmkq81i67qjpwjd4jdaxp2-findutils-4.6.0/bin/find: cannot execute binary file: Exec format error
> /nix/store/1xi5xjj34d1inamh559ddq16ixgkwl1j-nix-prefetch-git: line 302: /nix/store/dhmqrk1mj2kmkq81i67qjpwjd4jdaxp2-findutils-4.6.0/bin/xargs: cannot execute binary file: Exec format error
> removing `.git'...
> builder for ‘/nix/store/jvpilixgm4cchg32jsfqyzwg0cw8ydrz-FreetypeGL-286b758.drv’ failed with exit code 126
> cannot build derivation ‘/nix/store/qm5477lxxgvm176kq366hlm2l020xaqb-freetype-gl-0.2.0.0.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/c3i3zfcxdy3q6wh5msk3w0l1jjs3ap0a-graphics-drawingcombinators-1.7.1.drv’: 1 dependencies couldn't be built
> killing process 7713
> cannot build derivation ‘/nix/store/104ai0wg3jwcvlif066kqmd5f65rp8d8-Lamdu-0.1.drv’: 1 dependencies couldn't be built
> error: build of ‘/nix/store/104ai0wg3jwcvlif066kqmd5f65rp8d8-Lamdu-0.1.drv’ failed

It is possible to move the nix expressions to nixpkgs repository - I don't know yet how. But after they would be added there you could do a local build using:

    nix-build -E with import <nixpkgs> {}; haskellPackages.lamdu.overrideDerivation (drv: { src = ./.; })

Did nix-build work on your system?

**Comment by yairchu** [comment] 2018-02-12 13:40
@razvan-panda iiuc it failed building FreetypeGL, that seems unrelated to my changes. Can you bisect on when that started?

> Did nix-build work on your system?

I'm now installing nix-build so I can check on my macOS system. I've heard some accounts that nix doesn't work well on macOS but I guess I'll find out..

**Comment by razvan-panda** [comment] 2018-02-12 13:45
@yairchu When the nix expressions [were modified](https://github.com/lamdu/lamdu/commit/0a2ef60281395051aee2dfeb186d1e828e287970) is when it started. Revert the changes to them and it will build again. I don't know how to fix the current Nix error yet, but I might have a look at it later.

**Comment by yairchu** [comment] 2018-02-12 13:53
For me `nix-build` doesn't work on macOS even before these changes, failing with:

    dyld: Library not loaded: /private/tmp/nix-build-leveldb-1.18.drv-0/source/libleveldb.dylib.1
    Referenced from: /private/tmp/nix-build-leveldb-haskell-0.6.5.drv-0/leveldb-haskell-0.6.5/dist/build/Database/LevelDB/C_hsc_make
    Reason: image not found
    running dist/build/Database/LevelDB/C_hsc_make failed (exit code -6)
    command was: dist/build/Database/LevelDB/C_hsc_make  >dist/build/Database/LevelDB/C.hs
    builder for ‘/nix/store/klasldqwyiddpify9r32qh9w950afijl-leveldb-haskell-0.6.5.drv’ failed with exit code 1

**Comment by razvan-panda** [comment] 2018-02-12 13:55
@yairchu I only packaged it for NixOS/Linux, for MacOS/WSL etc. it would need to be tweaked to build.

**Comment by razvan-panda** [comment] 2018-02-12 14:31
@yairchu It wasn't building earlier on NixOS because I got some nix-store corrupted caused by a forced VM close. Did a `nix-store --verify --check-contents --repair` and then installing it worked fine.

**Comment by razvan-panda** [comment] 2018-02-12 18:06
@yairchu Any ideas if it is possible to gain access to some MacOS VM to implement the Nix build for it also? All I could find are requiring hacking VMware for example for it to work.

**Comment by yairchu** [comment] 2018-02-13 10:28
I don't know, but perhaps it's not necessary as it seems that I have updated the nix files successfully..

Still the [previous question](https://github.com/lamdu/lamdu/issues/84#issuecomment-364890823) stands - whether it's possible to achieve this within stack without the need to maintain additional build files.

**Comment by razvan-panda** [comment] 2018-02-13 11:33
To guarantee reproducible builds is required to use Nix (or something better which doesn't exist yet afaik).
Stack is less flaky than Cabal Install but it still fails too many times.
I will need to move the .nix expressions into the nixpkgs repository so that everyone can install Lamdu without cloning this repository. But unfortunately, I do not know enough Nix language yet to do that.

To answer your question - if you want reliable builds on any machine you could switch focus on using  Cabal + Nix. Nix is guaranteed to build on any machine as long as you manage to build it once while stack fails randomly on different machines (I wasted countless hours on failed Stack builds).

If those Haskell dependencies of Lamdu were on Hackage they would have gotten automatically generated nix-expressions using cabal2nix afaik. But many of those dependencies of Lamdu are forks so I am not sure how to work around that.

**Comment by yairchu** [comment] 2018-02-13 11:45
@razvan-panda 
> To guarantee reproducible builds is required to use Nix (or something better which doesn't exist yet afaik).
Stack is less flaky than Cabal Install but it still fails too many times.

Stack has the same purpose and vision:

> It has a strong focus on reproducible build plans

(From "Why Stack?" section [here](https://haskellstack.org/))

Also, from the experience you shared it seems that nix may be flaky too sometimes.

We use stack exactly because we want reproducible builds. Using nix+cabal could be a valid option too but those are less popular tools afaik which also require more installation..

**Comment by razvan-panda** [comment] 2018-02-13 12:37
> Also, from the experience you shared it seems that nix may be flaky too sometimes.

Are you talking about when it would not build because the virtual machine died? Nix operations are atomic but they do not account for lying about what was written or not to disk already because the VM died.

Stack doesn't have good enough guarantees of reproducibility, it is just better than cabal install. I wasted countless hours on failed stack build - this ticket is just one of those countless examples.

Meanwhile, I wasted no time on failed Nix builds. Why? Because with Nix same inputs generate same outputs. If you packaged something with Nix you have a very strong guarantee that it will build correctly in the future on your and any other machine.

Stack or Cabal, doesn't matter that much - but something reliable like Nix needs to be used on top.

**Comment by yairchu** [comment] 2018-02-13 13:29
> If you packaged something with Nix you have a very strong guarantee that it will build correctly in the future on your and any other machine.

So far that's not my experience, having this very build not work on my own machine with nix.

But that's expectable, because you said

> I only packaged it for NixOS/Linux

and that's totally fine.

> I wasted countless hours on failed stack build - this ticket is just one of those countless examples.

Similarly to nix in this instance I suppose also stack-based builds may sometimes need some tweaking to work on new os's.

**Comment by razvan-panda** [comment] 2018-02-13 21:41
@yairchu Here's an example of Stack's lack of reliability: https://github.com/lamdu/lamdu/issues/86
Examples speak louder than words. Builds just fine using Nix on the same system.

**Comment by yairchu** [comment] 2018-02-14 08:53
@razvan-panda 
Ok, you are indeed very right in that nix's scope is wider than stack's in terms of non-haskell system dependencies which stack does not install for you, which requires additional platform-dependent installation instructions for different platforms (`apt-get` lines etc).

**Comment by razvan-panda** [comment] 2018-02-14 12:24
My point was that stack is unreliable and if you wish to deliver Lamdu reliably you need to package it with Nix (or something better).

Both Stack and Cabal integrate with Nix but Stack can and will still fail on building certain Haskell projects regardless of non-Haskell dependencies - I observed this countless times.
